### PR TITLE
Anuncio dao

### PR DESCRIPTION
**Pull request by gabriellemos**
This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/23)

### CODE REVIEW

**Comment by ddspog** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/controllers/Application.java, line 35 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGOZKjoo1PDCn6FKKLx:-KGOZKjoo1PDCn6FKKLy:-798993836) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L35)):_
Pra que isso?????

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Comment by ddspog** [comment]
Reviewed 1 of 29 files at r2.
Review status: 2 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Application.java, line 45 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGO_QLnpZSOHapzV20D:-KGO_QLnpZSOHapzV20E:-640368923) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L45)):_
Esse tipo de coisa não se commita

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Comment by ddspog** [comment]
Review status: 2 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/models/Confeiteiro.java, line 45 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGOaZA-O3PUxPLyYGc0:-KGOaZA0skC7bzH7Sd1l:-1875451215) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/models/Confeiteiro.java#L45)):_
Desnecessário.

---

_[app/models/Confeiteiro.java, line 68 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGOaiFxccjg5GRb2h5h:-KGOaiFxccjg5GRb2h5i:-369701918) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/models/Confeiteiro.java#L68)):_
Depois precisa recodificar o arquivo para UTF-8, para tirar esses ç com problema

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Comment by andrewfnw** [comment]
Review status: 2 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/Application.java, line 35 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGOZKjoo1PDCn6FKKLx:-KGOhbqWmqI_xKQ3BMhG:-1151309615) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L35)):_
Isso foi pq tava dando erro, aí pra testar foi comentado e colocado isso aí só pra compilar pra poder testar, mas hoje de manhã na reunião, a gente testou com as linhas do jeito que tava antes e funcionou, falta integrar com o front end atualizado.

---

_[app/controllers/Application.java, line 45 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGO_QLnpZSOHapzV20D:-KGOiHaJHx-vYByR8vVf:-1490601278) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L45)):_
mesma coisa do anterior

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Comment by gabriellemos** [comment]
Review status: 2 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Application.java, line 35 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGOZKjoo1PDCn6FKKLx:-KGP7eYFexLvlvAK-44e:-499146009) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L35)):_
Done.

---

_[app/controllers/Application.java, line 45 [r3]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23#-KGO_QLnpZSOHapzV20D:-KGP7jSe3NqIVtRC3Qz6:-499146009) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/3a85a4f4caadb557ab07d231454018224a78ac84/app/controllers/Application.java#L45)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Comment by alineatcosta** [comment]
Reviewed 2 of 25 files at r1, 28 of 29 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/23)_

**Pull request merged**
