### PR TITLE
Adicionando imagens no projeto

### PR DESCRIPTION
**Pull request by ddspog**
As imagens que estávamos usando eram de uma álbum no Picasa. Agora vamos usar imagens do projeto, sendo mais fáceis de alterar, apenas editando-as diretamente no projeto.

---

This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/9)

### CODE REVIEW

**Comment by gabriellemos** [comment]
Qual o objetivo em adicionar os hrefs nos html ui-sref?

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-:-KErvq7IqeE9CNdXMbSK:1199668334)_

**Comment by gabriellemos** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9)_

**Comment by gabriellemos** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[public/html/home/directives/footbar.html, line 1 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-KEs9Bx7sKwUMrfOSEOj:-KEs9Bx81BT4LzIBtzfc:-413085920) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/ded7262a973132741ccc09c7e84698c418aedd32/public/html/home/directives/footbar.html#L1)):_
Aguardando resposta

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9)_

**Comment by ddspog** [comment]
Se você não adicionar um default para #, o angularjs gera um href de #/, que dá erro em jQuery... 

Na verdade, esse erro de routing é um bug chato e ainda não o consertei satisfatoriamente. Talvez ele não apareça usando Heroku.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[public/html/home/directives/footbar.html, line 1 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-KEs9Bx7sKwUMrfOSEOj:-KEsn20tr2zRiJEssn0Y:166874) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/ded7262a973132741ccc09c7e84698c418aedd32/public/html/home/directives/footbar.html#L1)):_
?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-:-KEsmeNABIHJI43WsSel:1668853020)_

**Comment by gabriellemos** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[public/html/home/directives/footbar.html, line 1 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-KEs9Bx7sKwUMrfOSEOj:-KEuglonLn_dot148zrO:-1077169822) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/ded7262a973132741ccc09c7e84698c418aedd32/public/html/home/directives/footbar.html#L1)):_
Ali em cima: Qual o objetivo em adicionar os hrefs nos html ui-sref?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9)_

**Comment by gabriellemos** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/9#-:-KFJt5sh68TUicmm9XsH:1417088721)_

**Pull request merged**
