### PR TITLE
Adiciona interface gráfica para o Feed de Anúncios

### PR DESCRIPTION
**Pull request by ddspog**
Um básico da interface já foi criada. Com isso, podemos ir trabalhando no carregamento de anúncios para o site.

---

This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/10)

### CODE REVIEW

**Comment by gabriellemos** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[app/controllers/Application.java, line 53 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KErwqHn-xuIwMV2tc0_:-KErwqHoXZQ7Fyj7UvHh:1419714957) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/app/controllers/Application.java#L53)):_
Dei uma checada na implementação no getAds em Text e ele está sempre retornando:
-> ObjectNode result = Json.newObject();
O que isso está fazendo exatamente porque me aparente ser sempre um JSON vazio

---

_[app/views/feed/head.scala.html, line 11 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEugyLT4jagOUaKXbHL:-KEugyLT4jagOUaKXbHM:487365200) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/app/views/feed/head.scala.html#L11)):_
Pq essa keyword em ingles?

---

_[conf/routes, line 6 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhIt0Te59a1-ikPkL:-KEuhIt0Te59a1-ikPkM:-1312215985) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/conf/routes#L6)):_
No commit de @andrewfnw ele colocou: 

@controllers.Application.index()

tem alguma diferença?

---

_[public/html/feed/directives/navbar.html, line 5 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhfyoE18dZP2sIt9F:-KEuhfypxp3slRTXCj_3:-1938997800) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/feed/directives/navbar.html#L5)):_
Isso aparece na Interface né? Corrija para pt-br já que o site é brasileiro.

---

_[public/html/home/directives/footbar.html, line 7 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhwZGH0bBze-h4ceo:-KEuhwZGH0bBze-h4cep:-668384328) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/home/directives/footbar.html#L7)):_
Ainda não entendi o motivo desse href pra canto nenhum se vc tem ui-sref="{{btn.url}}" com o link 

---

_[public/html/home/directives/navbar.html, line 9 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEui7M_Bl-iLxzViOai:-KEui7M_Bl-iLxzViOaj:479810121) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/home/directives/navbar.html#L9)):_
Mesmo comentário do href

---

_[public/html/home/directives/navbar.html, line 15 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEui9geOBr9A4WYDw1W:-KEui9geOBr9A4WYDw1X:479810121) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/home/directives/navbar.html#L15)):_
Mesmo comentário do href

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiTDuy5bJFxd3rRqS:-KEuiTDuy5bJFxd3rRqT:-385906641) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/javascripts/feed/controllers.js#L19)):_
Só me confirma uma coisa, aqui vai ser onde a gente vai receber o JSON com os Anuncios já armazenados no sistema né?

---

_[public/json/feed/FootbarDefault.json, line 8 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiyjf3LFem8gYFjUM:-KEuiyjf3LFem8gYFjUN:1670672299) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/FootbarDefault.json#L8)):_
Se lembre que o site é em pt-br

---

_[public/json/feed/NavbarDefault.json, line 6 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuj5asyCjMmTzZ_o3I:-KEuj5asyCjMmTzZ_o3J:2050800713) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/NavbarDefault.json#L6)):_
Isso é pq ainda não tem usuário logado no sistema né? Não seria melhor deixar logo como Anônimo?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Comment by ddspog** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[app/controllers/Application.java, line 53 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KErwqHn-xuIwMV2tc0_:-KF194snEIuYIok_ticg:-425466331) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/app/controllers/Application.java#L53)):_
Exatamente.
Isso é feito para que em outro commit, ele realmente retorne alguma coisa...
Faltou eu explicar em comentários isso.

---

_[app/views/feed/head.scala.html, line 11 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEugyLT4jagOUaKXbHL:-KF19DZ_Tbh2ZfCpe0I3:-793463445) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/app/views/feed/head.scala.html#L11)):_
Porque tem brasileiros que pesquisam em inglês tbm. Para procurar algo, até mesmo no Brasil.

---

_[conf/routes, line 6 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhIt0Te59a1-ikPkL:-KF19Lhv1F7Ak6wOEE_y:1770771601) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/conf/routes#L6)):_
Não. Tirar os () só reforça que o método não tem parâmetro nenhum.

---

_[public/html/feed/directives/navbar.html, line 5 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhfyoE18dZP2sIt9F:-KF19Us9T96LJ7sc8me1:-1446347005) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/feed/directives/navbar.html#L5)):_
Aparece não. Isso veio no template... Não sei para que serve.

---

_[public/html/home/directives/footbar.html, line 7 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuhwZGH0bBze-h4ceo:-KF19aGZR-qRUIv9nsNI:-1937083999) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/html/home/directives/footbar.html#L7)):_
Corrigir um erro do JQuery. Eu também não entendo. 

Mas isso tem uma outra função. <a href="#"></a> garante que o site não seja redirecionado para nenhum outro link.

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiTDuy5bJFxd3rRqS:-KF1A0Sinbllq8Ji443F:-1979241589) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/javascripts/feed/controllers.js#L19)):_
Vai. Quando o método de prover os JSON do sistema tiver sido feito, eu vou deletar esse template aqui, e deixar aquilo que tá em comment.

---

_[public/json/feed/FootbarDefault.json, line 8 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiyjf3LFem8gYFjUM:-KF1AC5B1bcS0YTtrzko:998068540) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/FootbarDefault.json#L8)):_
Sim... Me esqueci desse trecho. 

---

_[public/json/feed/NavbarDefault.json, line 6 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuj5asyCjMmTzZ_o3I:-KF1AJWeYFBClUnR6ab0:-1008555892) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/NavbarDefault.json#L6)):_
...
Na verdade seria melhor deixar nada ali. Vou ver como fazer isso.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Comment by gabriellemos** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[public/json/feed/FootbarDefault.json, line 8 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiyjf3LFem8gYFjUM:-KF1rOnrVHLIQFsdLjqt:1847221193) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/FootbarDefault.json#L8)):_
Arrume a acentuação de ícone.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Comment by ddspog** [comment]
Review status: 35 of 37 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_[public/json/feed/FootbarDefault.json, line 8 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10#-KEuiyjf3LFem8gYFjUM:-KF1tCe4Hax2k5hWzj2W:676635175) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/7fd41d775c60ef071ddd841421d75598659df3bb/public/json/feed/FootbarDefault.json#L8)):_
Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Comment by gabriellemos** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Comment by gabriellemos** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/10)_

**Pull request merged**
