### PR TITLE
Integrar listagem de anúncios na UI

### PR DESCRIPTION
**Pull request by ddspog**
Eu implementei uma maneira de empacotar todos os anúncios dos banco de dados em JSON. Esse resultado vai para o front-end, que será responsável por mostrar o resultado.

---

This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/17)

### CODE REVIEW

**Comment by gabriellemos** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Text.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDz4AcKl3YTQusVyHa:-KFDz4AcKl3YTQusVyHb:1828028644) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/app/controllers/Text.java#L40)):_
Eu ainda acho melhor deixar todos com a mesma imagem pra evitar a falsa impressão de que está implementada a imagem no sistema da gente.

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDzOieDSD-Lkmt6SaP:-KFDzOieDSD-Lkmt6SaQ:927252774) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/public/javascripts/feed/controllers.js#L19)):_
Já que isso não está mais sendo utilizado, pode remover.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17)_

**Comment by ddspog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Text.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDz4AcKl3YTQusVyHa:-KFFAaUqQEL6DBvlDcAl:1936712862) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/app/controllers/Text.java#L40)):_
As imagens são necessárias para alguns detalhes do front-end. Até para saber questão de cor a usar nas barras.

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDzOieDSD-Lkmt6SaP:-KFFAV-i9TX_FeRKKPuf:1166290387) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/public/javascripts/feed/controllers.js#L19)):_
Ainda não. Quando criarmos anúncios teste, usaremos esses parâmetros.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17)_

**Comment by gabriellemos** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Text.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDz4AcKl3YTQusVyHa:-KFFDj9lP_17BinNkkT8:1224068666) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/app/controllers/Text.java#L40)):_
Tipo, eu entendo o porquê das imagens mas não vejo motivo pra ter mais de uma principalmente pra ser sempre escolhido uma imagem por um random

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDzOieDSD-Lkmt6SaP:-KFFF2_F_p5x_sTKLZHJ:1195230724) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/public/javascripts/feed/controllers.js#L19)):_
Adicionei uma task em extra pra fazer isso e coloquei essas informações na descrição de lembrete na hora de adicionar o bd.

Pode remover o código agora.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17)_

**Comment by ddspog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/Text.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDz4AcKl3YTQusVyHa:-KFFGLVaBE_gmmPjFR0p:-795783413) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/app/controllers/Text.java#L40)):_
Foi por capricho mesmo. Queria um exemplo bem feito, aí simplesmente peguei um álbum de bolos e fui copiando os links da imagens. Gosto de um exemplo bem populado.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17)_

**Comment by ddspog** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[public/javascripts/feed/controllers.js, line 19 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-KFDzOieDSD-Lkmt6SaP:-KFGBklpTb2L_ituts3t:-469593373) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/5e07f731edf8ddb259f17b794dafc719cb13b11e/public/javascripts/feed/controllers.js#L19)):_
done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17)_

**Comment by gabriellemos** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/17#-:-KFGGQTnmeOQS0wgUwNe:1417088721)_

**Pull request merged**
