### PR TITLE
Facebook login

### PR DESCRIPTION
**Pull request by andrewfnw**
This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/18)

### CODE REVIEW

**Comment by gabriellemos** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/Application.java, line 25 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJrY5vKrreix8A1Tqo:-KFJrY5vKrreix8A1Tqp:-834806891) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/app/controllers/Application.java#L25)):_
Verifica se já tem algum usuário conectado. Se tiver redireciona pra página de feeds, caso contrário redireciona para a home.

É isso mesmo? Se for atualize o javaDoc

---

_[app/controllers/Application.java, line 63 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJs3IiPvftEGfKzeep:-KFJs3IjE_DLqauTPMoF:-1659349802) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/app/controllers/Application.java#L63)):_
método chamado ao finalizar o login com facebook?

---

_[conf/routes, line 15 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJsXAarRTp571j0qkk:-KFJsXAarRTp571j0qkl:-739106571) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/conf/routes#L15)):_
Já está integrado?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by andrewfnw** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[app/controllers/Application.java, line 25 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJrY5vKrreix8A1Tqo:-KFK8TgnBIJcnOXpSD2z:-1579207045) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/app/controllers/Application.java#L25)):_
Certo, já estou atualizando.

---

_[app/controllers/Application.java, line 63 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJs3IiPvftEGfKzeep:-KFK8laaBPnTWoZAkEXX:-169537590) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/app/controllers/Application.java#L63)):_
Não, ele faz a chamada para a página que faz o login no facebook.

---

_[conf/routes, line 15 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJsXAarRTp571j0qkk:-KFK9J9PV1RXGw7PkxLn:1317637258) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/conf/routes#L15)):_
Ele já redireciona para o login do facebook.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by gabriellemos** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[conf/routes, line 15 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJsXAarRTp571j0qkk:-KFKEnMuFa-G7WYnOa2d:-1532638886) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/conf/routes#L15)):_
Eu perguntei do /logout

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by andrewfnw** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[conf/routes, line 15 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJsXAarRTp571j0qkk:-KFKF_cKFkYkrGSPVwEQ:-753573804) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/conf/routes#L15)):_
Acredito que funcionaria, mas acho que na página do feed ele não aceita logout ainda, pode ver que sempre fica com o mesmo nome de Dennis lá em cima, mesmo apertando o botão de logout, não acontece nada, não deve estar configurado ainda no html.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by alineatcosta** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by ddspog** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by ddspog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[conf/routes, line 15 [r2]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18#-KFJsXAarRTp571j0qkk:-KGPvi0Swom9pi0YXnmX:-374774835) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/8b002209a239f570a5e8315b046120b515b45086/conf/routes#L15)):_
O logout só precisa do botão. Vou trabalhar nele depois. Acredito que funcione sem nenhum problema.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Comment by alineatcosta** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/18)_

**Pull request merged**
