### PR TITLE
Configuracao do bd local

### PR DESCRIPTION
**Pull request by gabriellemos**
This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/30)

### CODE REVIEW

**Comment by jordangba** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[app/models/Confeiteiro.java, line 190 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30#-KGoRzdvbysdMOgwHdsi:-KGoRzdvbysdMOgwHdsj:-1163163013) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/6d925439925af142a96539f3629e22eab14a470b/app/models/Confeiteiro.java#L190)):_
método defasado, visto quer email, contato e endereço possui seu próprio model, sendo necessário refazer o equal.

---

_[app/models/dao/Tabelas/ScriptSQL.java, line 81 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30#-KGoSL29bGD89WrF89W1:-KGoSL29bGD89WrF89W2:-197907414) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/6d925439925af142a96539f3629e22eab14a470b/app/models/dao/Tabelas/ScriptSQL.java#L81)):_
falta uma coluna(erro meu) nome sqlBuilder.append("Disponibilidade_Anuncio\t\tBOOLEAN\t\tDEFAULT TRUE\tNOT NULL, "); (creio que seria assim o comando, a ser implementado, mas se quise pode usa alter table que  seria = ALTER TABLE Anuncio  ADD Disponibilidade_Anuncio\t\tBOOLEAN\t\tDEFAULT TRUE\tNOT NULL;

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by jordangba** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by gabriellemos** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/models/dao/Tabelas/ScriptSQL.java, line 81 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30#-KGoSL29bGD89WrF89W1:-KGoV4P2YvuK28OMEJeS:-499146009) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/6d925439925af142a96539f3629e22eab14a470b/app/models/dao/Tabelas/ScriptSQL.java#L81)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by gabriellemos** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by jordangba** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by jordangba** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Comment by jordangba** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/30)_

**Pull request merged**
