### PR TITLE
vai carretaFuracão

### PR DESCRIPTION
**Pull request by jordangba**
This change is [Reviewable](https://reviewable.io/reviews/gabriellemos/projetoles-2015.2/33)

### CODE REVIEW

**Comment by gabriellemos** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[app/models/Email.java, line 9 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBaN4UeJ9nudkqWIwW:-KHBaN4VVHUReqHn5usQ:672328982) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/Email.java#L9)):_
private rapaz...

---

_[app/models/dao/Anuncio_DAO.java, line 191 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBa_fGMAO05IJnAYri:-KHBa_fGMAO05IJnAYrj:1459668643) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/299ea7208d68c5ef239bed37749a3021e8caa1ca/app/models/dao/Anuncio_DAO.java#L191)):_
Não seria mais interessante usar um LIKE ao invés do igual?

---

_[app/models/dao/Confeiteiro_DAO.java, line 37 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBcJmWXzdLPyiatDhR:-KHBcJmXhgNhCIQ3WWfM:451857958) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Confeiteiro_DAO.java#L37)):_
muda essa implementação para:

inserirConfeiteiro(conf.getNome(), conf.getIdFacebook());

ou na outra implementação faça:

Confeiteiro conf = new Confeiteiro(nome, idFacebook);
inserirConfeiteiro(conf);

---

_[app/models/dao/Contato_DAO.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBdXUPhmmWd1PFs1tt:-KHBdXUPhmmWd1PFs1tu:582386087) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Contato_DAO.java#L40)):_
Mesmo comentário que em ConfeiteiroDAO

---

_[app/models/dao/Contato_DAO.java, line 92 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBdr-AxksrfalizE_d:-KHBdr-BMYd-CM93w_Ro:1607222028) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Contato_DAO.java#L92)):_
Na moral, isso realmente é preciso? Ainda sou contra esse método

---

_[app/models/dao/Email_DAO.java, line 65 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBe60iotFrsOUudPHE:-KHBe60iotFrsOUudPHF:1607222028) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Email_DAO.java#L65)):_
Na moral, isso realmente é preciso? Ainda sou contra esse método

---

_[app/models/dao/Endereco_DAO.java, line 39 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBg4DZUynLyzKdXbTI:-KHBg4D_4JH_s6ESyxgy:1349263107) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Endereco_DAO.java#L39)):_
O mesmo já citado antes..

---

_[app/models/dao/Endereco_DAO.java, line 93 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBgADt7jvfujbAqjte:-KHBgADt7jvfujbAqjtf:1349263107) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Endereco_DAO.java#L93)):_
O mesmo já citado antes..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33)_

**Comment by jordangba** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[app/models/dao/Anuncio_DAO.java, line 191 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBa_fGMAO05IJnAYri:-KHBk7geop2MdFjQ6S1m:-7500686) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/299ea7208d68c5ef239bed37749a3021e8caa1ca/app/models/dao/Anuncio_DAO.java#L191)):_
LIKE compra com subString, tipo 1/01/01 seu eu coloca 1 iria parece resultados com a data 1, 10-19 não sendo o foco da pesquisa, so se usa LIKE para tipi eu quero busca todas as datas que tenham 1, e esse não o caso , e ainda mais esse parametro ja foi retirado.

---

_[app/models/dao/Confeiteiro_DAO.java, line 37 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBcJmWXzdLPyiatDhR:-KHBlkkr_HEmzBlbGCnv:210444745) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Confeiteiro_DAO.java#L37)):_
pode ser.

---

_[app/models/dao/Contato_DAO.java, line 92 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBdr-AxksrfalizE_d:-KHBl_ooosyJqhyjMBG9:-1919489255) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Contato_DAO.java#L92)):_
infelizmente por preguiça dos outros em usa o ID.

---

_[app/models/dao/Email_DAO.java, line 65 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBe60iotFrsOUudPHE:-KHBlgoF-uOYOFzjh-qk:-1919489255) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Email_DAO.java#L65)):_
infelizmente por preguiça dos outros em usa o ID.

---

_[app/models/dao/Endereco_DAO.java, line 39 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBg4DZUynLyzKdXbTI:-KHBli0xaGUjuEafwcSp:-1919489255) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Endereco_DAO.java#L39)):_
infelizmente por preguiça dos outros em usa o ID.

---

_[app/models/dao/Endereco_DAO.java, line 93 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBgADt7jvfujbAqjte:-KHBlidK5hfg2_TxqOhF:-1919489255) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Endereco_DAO.java#L93)):_
infelizmente por preguiça dos outros em usa o ID.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33)_

**Comment by gabriellemos** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[app/models/dao/Anuncio_DAO.java, line 191 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBa_fGMAO05IJnAYri:-KHCj7jtfokwzWHMUV9t:1796102875) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/299ea7208d68c5ef239bed37749a3021e8caa1ca/app/models/dao/Anuncio_DAO.java#L191)):_
<details><summary>

<i>Previously, jordangba wrote…</i></summary>



> LIKE compra com subString, tipo 1/01/01 seu eu coloca 1 iria parece resultados com a data 1, 10-19 não sendo o foco da pesquisa, so se usa LIKE para tipi eu quero busca todas as datas que tenham 1, e esse não o caso , e ainda mais esse parametro ja foi retirado.</details>
> Mas a pesquisa não é no campo cidade? É comum a pessoa digitar só Campina ao invés de campina grande, da mesma forma que o like evita problemas de 'João Pessoa' e 'Joao pessoa' não? Entendo que digitando só campina apareceriam outros resultados mas acho melhor do que obrigar ao cara de escrever o nome da cidade 100% correto da forma que está armazenada no BD.

---

_[app/models/dao/Contato_DAO.java, line 40 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBdXUPhmmWd1PFs1tt:-KHCk4Su8hRTYxfu6ZA-:-830206235) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Contato_DAO.java#L40)):_
<details><summary>

<i>Previously, gabriellemos (Gabriel) wrote…</i></summary>



> Mesmo comentário que em ConfeiteiroDAO</details>
> Esqueceu de checar esse aqui

"
muda essa implementação para:

inserirConfeiteiro(conf.getNome(), conf.getIdFacebook());

ou na outra implementação faça:

Confeiteiro conf = new Confeiteiro(nome, idFacebook);
inserirConfeiteiro(conf);
"

só que ao invés de confeiteiro seria Contato

---

_[app/models/dao/Endereco_DAO.java, line 39 [r1]](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33#-KHBg4DZUynLyzKdXbTI:-KHCjv2KoncZq06igB6C:213028562) ([raw file](https://github.com/gabriellemos/projetoles-2015.2/blob/0beffe209a7eda9060a40f8928846e89f35f1511/app/models/dao/Endereco_DAO.java#L39)):_
<details><summary>

<i>Previously, jordangba wrote…</i></summary>



> infelizmente por preguiça dos outros em usa o ID.</details>
> Esse aqui o pedido é diferente kkkk

"
muda essa implementação para:

inserirConfeiteiro(conf.getNome(), conf.getIdFacebook());

ou na outra implementação faça:

Confeiteiro conf = new Confeiteiro(nome, idFacebook);
inserirConfeiteiro(conf);
"

só que ao invés de confeiteiro seria Endereco

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33)_

**Comment by jordangba** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33)_

**Comment by gabriellemos** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gabriellemos/projetoles-2015.2/33)_

**Pull request merged**
